# Generated by Django 3.2.10 on 2021-12-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
