# Generated by Django 3.2.10 on 2021-12-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_uploadmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='file',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
